

try{
	let x = 1;
	throw new Error('test a throw');
}catch(e) {
	console.log(e);

}